(when (require 'zlc nil 'noerror)
  (zlc-mode t)
  (let ((map-z minibuffer-local-map))
    ;; (define-key map (kbd "<backtab>") 'zlc-select-previous)
    ;; (define-key map (kbd "S-<tab>")   'zlc-select-previous)
    (define-key map-z (kbd "C-n")  'zlc-select-next-vertical)
    (define-key map-z (kbd "C-p")    'zlc-select-previous-vertical)
    (define-key map-z (kbd "<right>") 'zlc-select-next)
    (define-key map-z (kbd "<left>")  'zlc-select-previous)
    (define-key map-z (kbd "C-c") 'zlc-reset)
    ;; (define-key map (kbd "C-f")       'zlc-select-next)
    ;; (define-key map (kbd "C-d")       'zlc-reset))
  (setq zlc-select-completion-immediately nil)
  ))
